### ISSUE TITLE
bundle exec pod install => ERR: No such file or directory

### ISSUE THREAD

**Issue by saiuya** [callstack/react-native-visionos#152] opened 2024-07-01 16:58 UTC
### Description

/Users/<username>/Library/Mobile Documents/com~apple~CloudDocs/<xxx>/code/RN/rnvisionos/node_modules/@callstack/react-native-visionos/sdks/hermes-engine/../../sdks/hermes-engine/utils/create-dummy-hermes-xcframework.sh
***
this path includes a space char, so can not find create-dummy-hermes-xcframework.sh file.

### Steps to reproduce

when run command: bundle exec pod install

### React Native Version

0.74.4

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
(node:26456) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 119.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: ~/.nvm/versions/node/v21.7.3/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v21.7.3/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
info Fetching system and libraries information...
(node:26456) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 119.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: ~/.nvm/versions/node/v21.7.3/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v21.7.3/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Reproducer

https://github.com/callstack/react-native-visionos/

### Screenshots and Videos

When Create your first App as "https://callstack.github.io/react-native-visionos-docs/docs/getting-started/create-first-app"
***
When it steps to "bundle exec pod install", I get this ERR message.

**Comment by okwasniewski** [comment] 2024-07-02 14:19
Hey, 

I couldn't reproduce your issue, can you create a project on a different path? Let's say `~/projects`?

**Comment by saiuya** [comment] 2024-07-02 14:34
Thank you for reply

I have put my project in another path, so that i resolved it。
However, when the path including a space, the create process will be in
error, could you fix this issue？thank you。
Btw, created project makes vscode typescript server deactivate, i would
give a tissue latter。

Yan

2024年7月2日(火) 23:20 Oskar Kwaśniewski ***@***.***>:

**Comment by okwasniewski** [comment] 2024-07-05 11:05
I'm not sure if react-native itself supports spaces in the path. I will double check that

**Comment by okwasniewski** [comment] 2024-07-08 11:44
Hey @saiuya,

I've checked this and it works for me without issues. It may be something else.. not a space. Some special character?

**Comment by saiuya** [comment] 2024-07-08 11:47
I put the project in Apple cloud before, so it contains a ~，maybe it is the
reason！

2024年7月8日(月) 20:44 Oskar Kwaśniewski ***@***.***>:

**Comment by okwasniewski** [comment] 2024-07-08 13:25
I've double checked looks like it was the space 👍🏻  Here is a PR to react-native which should fix it: https://github.com/facebook/react-native/pull/45316

**Comment by saiuya** [comment] 2024-07-08 13:33
> Hey @saiuya,
> 
> I've checked this and it works for me without issues. It may be something else.. not a space. Some special character?

- Hey, I try it again, I put the project in this path: 
`/Users/yy/Library/Mobile Documents/com~apple~CloudDocs/University/code/RN`
- When I get to the `visionos`  directory and  run the `bundle exec pod install` command, It returns error message as follow:
```shell
[!] /bin/bash -c 
set -e
. /Users/yy/Library/Mobile Documents/com~apple~CloudDocs/University/code/RN/rn_visionos/node_modules/@callstack/react-native-visionos/sdks/hermes-engine/../../sdks/hermes-engine/utils/create-dummy-hermes-xcframework.sh
/bin/bash: line 2: /Users/yy/Library/Mobile: No such file or directory
```
- Hope this tips help you.

**Comment by okwasniewski** [comment] 2024-07-30 08:18
The fix was merged upstream and should be included in upcoming releases.

**Closed by okwasniewski** 2024-07-30 08:18 UTC
Labels: bug
