### ISSUE TITLE
Building for archive to upload to app store fails

### ISSUE THREAD

**Issue by bartlomein** [callstack/react-native-visionos#127] opened 2024-03-07 16:33 UTC
### Description

Product -> Archive produces several bugs and the build fails. One is in `hermes-engine` and another one says it is being built for`visionOS-simulator` even though "Any VisionOS Device" is selected in the top build menu

### Steps to reproduce

Open Xcode and follow steps to build for App store deployment. 
Build app.

### React Native Version

0.73.4-1

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
none
```

### Stacktrace or Logs

```text
none
```

### Reproducer

none

### Screenshots and Videos

![Screenshot 2024-03-07 at 11 32 10 AM](https://github.com/callstack/react-native-visionos/assets/3741391/1c9c8416-f921-4763-ae0a-10afaa6658dc)
![Screenshot 2024-03-07 at 11 31 13 AM](https://github.com/callstack/react-native-visionos/assets/3741391/afbcfc7b-2c36-4457-bdc7-63ee66626c2a)

**Comment by bartlomein** [comment] 2024-03-07 18:30
I commented out the use of `vsnprintf` inside of `Logging.cpp` and it worked. However I'm guessing thats not a long term solution

**Comment by okwasniewski** [comment] 2024-04-12 07:22
Looks like this is a duplicate of #128 as the same issues are described by other people there - let's keep one of them open.

**Closed by okwasniewski** 2024-04-12 07:22 UTC
Labels: bug
