### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted.

### ISSUE THREAD

**Issue by saiuya** [callstack/react-native-visionos#153] opened 2024-07-03 09:16 UTC
### Description

I run the command yarn visionos(or npm run vision) to launch the vision pro simulator. However after a while, I get the vscode notification of "The JS/TS language service immediately crashed 5 times. The service will not be restarted". 
<img width="480" alt="image" src="https://github.com/callstack/react-native-visionos/assets/165663319/51881d2e-cad9-4831-8975-89721764d2a1">
***
I try to fix it as the follow link, But it didn't work for me.
https://github.com/microsoft/vscode/issues/212731#issuecomment-2110947019
https://github.com/microsoft/vscode/issues/212731#issuecomment-2126692616 
***
Without JS/TS language service, I can't go to the definition by shortcut "cmd + click", it is a big problem.
Can anyone give me some suggestions? Thank you.

### Steps to reproduce

1. brew install ruby (and set the enveriment variables )
2. npx @callstack/react-native-visionos@latest init YourApp
3. cd YourApp/visionos && bundle install
4. bundle exec pod install
5. cd ../ && npm run visionos
6. after about 5 minutes, vscode raise that "The JS/TS language service immediately crashed 5 times. The service will not be restarted."

### React Native Version

0.74.4

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 111.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.15.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman:
    version: 2024.06.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.3
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.74.3 is now available (your project is running on v0.74.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.2
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Stacktrace or Logs

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 111.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.15.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman:
    version: 2024.06.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.3
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.74.3 is now available (your project is running on v0.74.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.2
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Reproducer

https://github.com/callstack/react-native-visionos/

### Screenshots and Videos

<img width="480" alt="image" src="https://github.com/callstack/react-native-visionos/assets/165663319/51881d2e-cad9-4831-8975-89721764d2a1">

**Comment by saiuya** [comment] 2024-07-03 09:27
This is a complement, Although I have succeed to launch simulator, the problem is that vscode can't support JS/TS language service.
1. I am using vscode Version: 1.90.2
<img width="30%" alt="image" src="https://github.com/callstack/react-native-visionos/assets/165663319/4fc9e7ac-0fd5-41b5-b752-6539a2b65702">

**Comment by okwasniewski** [comment] 2024-07-05 11:04
Looks like a duplicate of #97 which got resolved, probably there is some regression happening. I will take a look at this.

**Comment by saiuya** [comment] 2024-07-08 13:53
> Looks like a duplicate of #97 which got resolved, probably there is some regression happening. I will take a look at this.

- I resolved this issue by this way which you have proposed:
https://github.com/callstack/react-native-visionos/issues/97#issuecomment-1931987729
- Thank you

**Comment by okwasniewski** [comment] 2024-09-17 10:38
Hey, can you check if this is still reproducible on the latest release (0.75)? I couldn't repro this

**Comment by okwasniewski** [comment] 2024-11-27 15:22
I'm closing this as stale, issue should be fixed.

**Closed by okwasniewski** 2024-11-27 15:22 UTC
